### ISSUE TITLE
Migrate all *.brannan.cloud apps/services to DigitalOcean

### ISSUE THREAD

**Issue by bananabrann** [bananabrann/brannan.cloud#70]
# TODO
- [x] Change nameservers
- [x] Move core brannan.cloud app
- [ ] Move files.brannan.cloud
- [x] Move chat.brannan.cloud
- [ ] Move tv.brannan.cloud

# Known Issues
- www.brannan.cloud doesn't work, most likely due to DNS propagation
